plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  instance-state-name: running

hostnames:
  - tag:Name

compose:
  ansible_host: >
    public_ip_address if tags.Role == 'bastion'
    else private_ip_address
  ansible_user: "'ubuntu'"

groups:
  bastion: tags.Role == 'bastion'
  monitoring: tags.Role == 'monitoring'
  node_exporter: tags.Role == 'node_exporter'

keyed_groups:
  - key: tags.OS
    separator: ""
