#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/prometheus
- name: Install dependencies
  package:
    name:
      - wget
      - tar
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin
    create_home: false

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: '0755'
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Prometheus binary
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0755'

- name: Deploy prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: Deploy systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify: restart prometheus

- name: Start Prometheus
  systemd:
    name: prometheus
    enabled: true
    state: started
    daemon_reload: true
